# This action renders PlantUML diagrams and pushes the
# resulting PNG file to your wiki repo.
#
# As it does not use the public PlantUML render service
# but an intance of the PlantUML Java app, this action
# doesnt leak your documentation to the public and can
# therefore be used in private repositories.

name: Render PlantUML to Wiki using latest PlantUML release
description: Action forked from frederikheld to allow more customization, published png to wiki from plantuml
branding:
  icon: file-text
  color: blue

inputs:
  WIKI_TOKEN:
      description: Secure token to access wiki repo
  GHAPP_TOKEN:
      description: Secure token to access wiki repo using GitHub Apps token
  INPUT_DIR:
      description: Directory in repo to read PlantUML source files from
      default: /input_directory
  OUTPUT_DIR:
      description: Directory in wiki to write rendered diagrams to
      default: /output_directory
  IMAGE_TYPE:
      description: Image type to use for rendering diagrams supported by PlantUML 
      default: png
  JAVA_ARGS:
      description: Additional Java arguments in case images need more memory
      default: "-DPLANTUML_LIMIT_SIZE=8192 -Xmx=1024m"

runs:
  using: "composite"
  steps:
    - name: Setup GitHub Action PATH
      shell: bash
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH

    - name: Call the plantuml and git script
      shell: bash
      env:
        WIKI_TOKEN: ${{ inputs.WIKI_TOKEN }}
        GHAPP_TOKEN: ${{ inputs.GHAPP_TOKEN }}
        INPUT_DIR: ${{ inputs.INPUT_DIR }}
        OUTPUT_DIR: ${{ inputs.OUTPUT_DIR }}
        IMAGE_TYPE: ${{ inputs.IMAGE_TYPE }}
        JAVA_ARGS: ${{ inputs.JAVA_ARGS }}
      run: entrypoint.sh
